// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7v7pROWVafC_Tv54zxxDOzfBA4wV_XZ0',
    appId: '1:297732993936:web:1e01eb00ff8c9eeb8bf915',
    messagingSenderId: '297732993936',
    projectId: 'wordpower-application123',
    authDomain: 'wordpower-application123.firebaseapp.com',
    databaseURL: 'https://wordpower-application123-default-rtdb.firebaseio.com',
    storageBucket: 'wordpower-application123.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArh4tRI_dy946O-Rl7lMp8BI2kQCW4k1o',
    appId: '1:297732993936:android:e089effa72555cb08bf915',
    messagingSenderId: '297732993936',
    projectId: 'wordpower-application123',
    databaseURL: 'https://wordpower-application123-default-rtdb.firebaseio.com',
    storageBucket: 'wordpower-application123.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8w0n5DCuL776ZrQnN5sJib9yhi5X0i74',
    appId: '1:297732993936:ios:542f191d5bb43ef88bf915',
    messagingSenderId: '297732993936',
    projectId: 'wordpower-application123',
    databaseURL: 'https://wordpower-application123-default-rtdb.firebaseio.com',
    storageBucket: 'wordpower-application123.appspot.com',
    iosClientId: '297732993936-9ns4smn5egms97a9eon0ko0clek4k7s9.apps.googleusercontent.com',
    iosBundleId: 'com.example.wordpowerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8w0n5DCuL776ZrQnN5sJib9yhi5X0i74',
    appId: '1:297732993936:ios:542f191d5bb43ef88bf915',
    messagingSenderId: '297732993936',
    projectId: 'wordpower-application123',
    databaseURL: 'https://wordpower-application123-default-rtdb.firebaseio.com',
    storageBucket: 'wordpower-application123.appspot.com',
    iosClientId: '297732993936-9ns4smn5egms97a9eon0ko0clek4k7s9.apps.googleusercontent.com',
    iosBundleId: 'com.example.wordpowerApp',
  );
}
